### ISSUE TITLE
add this project to https://json-schema.org/implementations.html?

### ISSUE THREAD

**Issue by karenetheridge** [yanick/jsonschematic#113]
I see this isn't listed at https://json-schema.org/implementations.html. If it's ready for prime time, please send a PR to https://github.com/json-schema-org/json-schema-org.github.io ! :)

**Comment by yanick** [comment]
Hi!

Way ahead of you: https://github.com/json-schema-org/json-schema-org.github.io/pull/346

... they seem to have forgotten about it, though. I'll give the ticket a bump presently.

**Comment by yanick** [comment]
It is done! :partying_face:
